# Generated by Django 5.0 on 2024-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_code", models.CharField(max_length=3)),
                ("playerXArr", models.JSONField(default=list)),
                ("playerOArr", models.JSONField(default=list)),
                ("gameState", models.BooleanField(default=False)),
            ],
        ),
    ]
