# Generated by Django 5.0 on 2024-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainGame", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="gameState",
            field=models.IntegerField(max_length=2),
        ),
    ]
