# Generated by Django 5.0 on 2024-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainGame", "0003_alter_gamesession_gamestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="gameState",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
