# Generated by Django 5.0 on 2024-02-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainGame", "0005_alter_gamesession_gamestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="numberOfMoves",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
