# Generated by Django 5.0 on 2024-03-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainGame", "0008_gamesession_gameturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="playerTurn",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
