# Generated by Django 5.0 on 2024-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="gameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameCode", models.CharField(max_length=8)),
                ("userTurn", models.CharField(max_length=8)),
                ("gameState", models.CharField(max_length=8)),
                ("xArr", models.JSONField(default=list)),
                ("oArr", models.JSONField(default=list)),
            ],
        ),
    ]
